param: {
        vehicleMass: 0.034,
        massThrust: 132000,
        kp_xy: 15.4,
        kd_xy: 9.2,
        ki_xy: 0.05,
        i_range_xy: 0.2,
        kp_z: 18.25,
        kd_z: 8.4,
        ki_z: 0.05,
        i_range_z: 0.4,
        # 70000 20000 
        kR_xy: 180000.0,
        kw_xy: 13000.0,
        ki_m_xy: 0.0,
        i_range_m_xy: 1.0,
        # 60000 12000
        kR_z: 60000.0,
        kw_z: 12000.0,
        ki_m_z: 500,
        i_range_m_z: 1500,
        kd_omega_rp: 200,
        #
        kpq_rates: 1.8,
        kr_rates: 0.3,
        #
        i_error_x: 0,
        i_error_y: 0,
        i_error_z: 0,
        i_error_m_x: 0,
        i_error_m_y: 0,
        i_error_m_z: 0,
}
